Models/AutocompleteModel.cs
namespace JeComplete.Models 
{
    public class AutocompleteModel
    {
        public string Id  { get; set; }
        public string name { get; set; }
        public string Url { get; set; }
        public string CallbackFunction { get; set; }
        public string DataText { get; set; }
        public string DataId { get; set; }
        public string Class { get; set; }
    }
}

Models/Home/IndexModel.cs
using System.Collections.Generic;
using JeComplete.Data;

namespace JeComplete.Models.Home 
{
    public class IndexModel
    {
        public List<Person> PeopleList {get; set;}
    }
}

Models/HomeIndexModel.cs
namespace JeComplete.Models
{
    public class HomeIndexModel
    {
        public AutocompleteModel Autocomplete { get; set; }
    }
}

Models/PeopleListModel.cs
using JeComplete.Data;
using System.Collections.Generic;

namespace JeComplete.Models 
{
    public class PeopleListModel
    {
        public List<Person> PeopleList { get; set; }
    }
}

Models/PersonnelFileModel.cs
using JeComplete.Data;

namespace JeComplete.Models
{
    public class PersonnelFileModel {
        public Person Person { get; set;}
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using JeComplete.Models;

namespace JeComplete.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> Logger;

        public HomeController(ILogger<HomeController> logger)
        {
            Logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            HomeIndexModel model = new HomeIndexModel();
            
            model.Autocomplete = new AutocompleteModel 
            {
                Id = "ddlSearch"
            };

            return View(model);
        }
    }
}

Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using JeComplete.Services;
using JeComplete.Models;

namespace JeComplete.Controllers
{
    public class PeopleController : Controller 
    {

        private readonly ILogger<HomeController> Logger;
        private readonly PersonService Service;

        public PeopleController (ILogger<HomeController> logger, PersonService service)
        {
            Logger = logger;
            Service = service;
        }

        [HttpGet] 
        public IActionResult Index()
        {
            PeopleListModel model = new PeopleListModel()
            {
                PeopleList = Service.GetPeopleList()
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult PersonnelFile(string id)
        {
            PersonnelFileModel model = new PersonnelFileModel
            {
                Person = Service.GetPerson(id)
            };

            if (model.Person != null)
                ViewData["Title"] = $"Dossier personnel de {model.Person.FirstName} {model.Person.LastName}";

            return View(model);
        }

        [HttpGet("People/SearchPeopleByNames/{query}")]
        public IActionResult SearchPeopleByNames(string query)
        {
            return Json(Service.SearchPeopleByNames(query));
        }
    }
}

Views/Home/Index.cshtml
@model JeComplete.Models.HomeIndexModel
@{
    ViewData["Title"] = "Accueil";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-sm-6 col-lg-4">
        <div class="form-group">
            <label for="ddlSearch" class="">Recherche</label>
                <partial name="~/Views/Shared/_Autocomplete.cshtml" for="Autocomplete" />
            </div>
        </div>
    </div>
</div>

Views/People/Index.cshtml
@model JeComplete.Models.PeopleListModel

@{
    ViewData["Title"] = "Répertoire";
}

<h1>@ViewData["Title"]</h1>

<div class="list-group">
    @foreach(var person in Model.PeopleList)
    {
        <a class="list-group-item list-group-item-action" asp-controller="People" asp-action="PersonnelFile" asp-route-id="@person.Id">@person.LastName, @person.FirstName</a>
    }
</ul>

Views/People/PersonnelFile.cshtml
@model JeComplete.Models.PersonnelFileModel
@using Bogus.DataSets

@if (Model.Person != null)
{
    <h1>@ViewData["Title"]</h1>
    <p>
        Prénom : @Model.Person.FirstName<br>
        Nom : @Model.Person.LastName<br>
        Date de naissance : @Model.Person.Birthdate.ToLongDateString()<br>
        Genre : @(Model.Person.Gender == Name.Gender.Female ? "Femme" : "Homme")<br>
        Rôle : @Model.Person.Role<br>
    </p>
}

Views/Shared/_Autocomplete.cshtml
@model JeComplete.Models.AutocompleteModel

<input type="hidden" id="hidDataId" />
<input type="text" class="form-control" id=@Model.Id />
<div class="list-group" id="lstResults">

<script>
    /* Parameters
        * Id : Identifier of the input control ( textbox )
        * Name : Name used in the form
        * Url : Url used for the search
        * Callback : Callback function when the user click on a list element
        * DataText : Template for the display of an list item
        * DataId: Id of the selected item
        * Class : Additionnal CSS class for the input control
    */

    var id = "@Model.Id";
    var lstResults = $("#lstResults");
    var hidDataId = $("#hidDataId");

    $(document).ready(() => {
        $(`#${id}`).keyup(ddlSearch_onKeyUp);
    });

    function ddlSearch_onKeyUp() {
        let term = $(`#${id}`).val();

        lstResults.children().remove();

        if (term !== null && term.length > 1) {
            $.get(`people/SearchPeopleByNames/${encodeURIComponent(term)}`, (list) => {
                if (list !== null) {

                    for (let item of list) {
                        displayResults(item);
                    }
                }
            });
        }
    }

    function displayResults(person) {
        let anchor = document.createElement("a");

        anchor.innerText = `${person.firstName} ${person.lastName}`;
        anchor.href = "#";
        $(anchor).attr("data-id", person.id);
        $(anchor).click(selectItem);
        $(anchor).addClass("list-group-item");
        $(anchor).addClass("list-group-item-action");
        lstResults.append(anchor);
    }

    function selectItem(event){
        event.preventDefault();
        let dataId = $(this).data("id");
        let dataText = $(this).html();
        hidDataId.val(dataId);
        $(`#${id}`).val(dataText);
        lstResults.empty();
    }
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr-CA">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JeComplete</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">JeComplete</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="People" asp-action="Index">Répertoire</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - JeComplete
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>